In [90]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [91]:
from fianco import *
from bot import *

brd = Engine().brd
brd[0, 0, -1] = False
brd[:, :, 9 // 2] = False
brd

array([[[ True,  True,  True,  True, False,  True,  True,  True, False],
        [False,  True, False, False, False, False, False,  True, False],
        [False, False,  True, False, False, False,  True, False, False],
        [False, False, False,  True, False,  True, False, False, False],
        [False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False]],

       [[False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False

In [92]:
unbin(1, brd)

array([[ 0, -1, -1, -1,  0, -1, -1, -1, -1],
       [ 0, -1,  0,  0,  0,  0,  0, -1,  0],
       [ 0,  0, -1,  0,  0,  0, -1,  0,  0],
       [ 0,  0,  0, -1,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  1,  0,  0,  0],
       [ 0,  0,  1,  0,  0,  0,  1,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  1,  0],
       [ 1,  1,  1,  1,  0,  1,  1,  1,  1]], dtype=int8)

In [93]:
unbin(0, brd)

array([[-1, -1, -1, -1,  0, -1, -1, -1, -1],
       [ 0, -1,  0,  0,  0,  0,  0, -1,  0],
       [ 0,  0, -1,  0,  0,  0, -1,  0,  0],
       [ 0,  0,  0, -1,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  1,  0,  0,  0],
       [ 0,  0,  1,  0,  0,  0,  1,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  1,  1,  1,  0,  1,  1,  1,  1]], dtype=int8)

In [94]:
krn = np.array([
    [1, 0, 1],
    [0, 1, 0],
    [1, 0, 1]
])
mat = np.array([
    [0, 0, 1, 0, 1],
    [0, 0, 0, 1, 0],
    [0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1],
])
conv2d(mat, krn)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'blit': Cannot determine Numba type of <class 'function'>

File "bot.py", line 101:
def make(capt: np.bool_, flip: bool, wrt: int, fr: YX, to: YX, brd: Mat) -> None:
    if capt:
    ^
